//=========================================================
// src/desperate_firefly_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{  //disable watchdog timer
   WDTCN = 0xDE; //First key
   WDTCN = 0xAD; //Second key
}

void hardware_config(void){
	// LED connected to Port 1 pin 3. i.e. P1.3
	//reduce port 1 drive strength
	PRTDRV&=~(PRTDRV_P1DRV__BMASK);
	//Port 1 pin 3 output mode open drain
	P1MDOUT&=~(P1MDOUT_B3__BMASK);
	// enable crossbar with weak pull up disabled
	XBR2=XBR2_XBARE__ENABLED|XBR2_WEAKPUD__BMASK;
	// configure system clock
	// System clock can be drop as low as 78,125 Hertz with appropriate settings of LFO0CN and CLKSEL registers.
	// first enable Low Frequency Oscillator with output divided by 8.
	LFO0CN=LFO0CN_OSCLEN__ENABLED|LFO0CN_OSCLD__DIVIDE_BY_8;
	// wait for oscillator ready bit.
	while ((LFO0CN&LFO0CN_OSCLRDY__SET)==0);
	// select LFO as system clock and divide that frequency again by 32
	// system clock is 80Khz/8/32=312,5 Hertz
	// T=1/Fsys=3,2msec
	CLKSEL=CLKSEL_CLKDIV__SYSCLK_DIV_32|CLKSEL_CLKSL__LFOSC;

}
// bit pattern to generate SOS morse code: dit,dit,dit,dah,dah,dah,dit,dit,dit
const char sos[4]={0xab,0xbb,0xaa,0};



//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
	unsigned char b,c;

// Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  hardware_config();
  b=0;
  while (1) 
  {
	c=sos[b/8]&(1<<(7-b%8));
    b++;
    if (b==28) b=0;
	if (c)
		P1&=~(1<<3); // port 1 pin 3 latch low LED ON
	else
		P1|=(1<<3); // port 1 pin 3 latch high  LED OFF
  }

}
