//=========================================================
// src/desperate_firefly_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{

}

// bit pattern to generate SOS morse code: dit,dit,dit,dah,dah,dah,dit,dit,dit
code char sos[4]={0xab,0xbb,0xaa,0};

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
	unsigned char b,c;

#define LED (1<<3)
// Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  b=0;
  while (1) 
  {
	  PCON0|=PCON0_IDLE__BMASK;
//	  P1^=LED;

	c=sos[b/8]&(1<<(7-b%8));
    b++;
    if (b==28) b=0;
	if (c)
		P1&=~(1<<3); // port 1 pin 3 latch low LED ON
	else
		P1|=(1<<3); // port 1 pin 3 latch high  LED OFF
  }

}
